# Generated by Django 4.1.3 on 2023-06-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utterance', models.CharField(max_length=5000)),
                ('answer', models.CharField(choices=[('opt1', 'opt1'), ('opt2', 'opt2'), ('opt3', 'opt3'), ('opt4', 'opt4')], max_length=4)),
                ('opt1', models.CharField(max_length=2000)),
                ('opt2', models.CharField(max_length=2000)),
                ('opt3', models.CharField(max_length=2000)),
                ('opt4', models.CharField(max_length=2000)),
                ('feedback', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastPage', models.CharField(choices=[('Landing', 'Landing'), ('Destacado', 'Destacado'), ('Arquitectura', 'Arquitectura'), ('Museo', 'Museo'), ('Gastronomía', 'Gastronomía'), ('Evaluacion', 'Evaluacion')], default='Landing', max_length=16)),
                ('lastCard', models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=-1, max_length=2)),
                ('test', models.ManyToManyField(related_name='questions', to='usuarios.question')),
            ],
        ),
    ]
