# Generated by Django 4.1.3 on 2023-06-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='lastCard',
            field=models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=-1),
        ),
    ]
