# Generated by Django 4.1.3 on 2023-06-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_session_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='test',
            new_name='questions',
        ),
    ]
